# Generated by Django 5.1.4 on 2025-01-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DroneModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=255)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0)),
            ],
        ),
    ]
