# Generated by Django 5.1.4 on 2025-01-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronemodels',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
